# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default=b'     ', max_length=5),
        ),
    ]
