# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default=b'mi direccion', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='name',
            field=models.CharField(default=b'mi informacion bancaria', max_length=50),
        ),
    ]
