# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=b'user_default_image.jpg', upload_to=b'photos'),
        ),
    ]
