# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 19:46
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0002_delete_ownuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
