# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0002_auto_20180319_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorprofile',
            name='collaborator_image',
            field=models.ImageField(blank=True, default=b'photos/perfil.jpg', upload_to=b'photos'),
        ),
    ]
