# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0002_auto_20180311_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='healthylifeapp.Category'),
            preserve_default=False,
        ),
    ]
