# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0002_auto_20180723_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(default=b'Mi direcci\xc3\xb3n de env\xc3\xado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='bank_name',
            field=models.CharField(default=b'Mi informaci\xc3\xb3n bancaria', max_length=50),
        ),
    ]
