# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0003_auto_20180319_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinformation',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
