# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0003_auto_20180314_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='header_image',
            field=models.BooleanField(default=False),
        ),
    ]
