# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0003_auto_20180928_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=b'photos/user_default_image.jpg', upload_to=b'photos'),
        ),
    ]
