# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0003_category_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Borrador'), (3, 'Eliminado')], default=3),
        ),
    ]
