# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0003_auto_20180226_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='photos'),
        ),
    ]
