# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0003_auto_20180302_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=b' '),
        ),
    ]
