# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0004_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=b'photos/perfil_miniatura.jpg', upload_to=b'photos'),
        ),
    ]
