# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0004_auto_20180311_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='healthylifeapp.Category'),
        ),
    ]
