# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0004_auto_20180929_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='collaborator_image',
            field=models.ImageField(blank=True, default=b'photos/user_profile.jpg', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.ImageField(blank=True, default=b'photos/user_profile.jpg', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=b'photos/user_profile.jpg', upload_to=b'photos'),
        ),
    ]
