# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0004_image_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=b'/image.jpg', upload_to=b'photos'),
        ),
    ]
