# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0005_auto_20181001_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='company',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='education',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='position',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
    ]
