# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0005_auto_20180501_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='fats',
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
    ]
