# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0006_auto_20180319_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=b'photos/perfil.jpg', upload_to=b'photos'),
        ),
    ]
