# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0006_auto_20181004_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'profile_image', '390x450', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.ImageField(blank=True, default=b'photos/default_company_image.jpg', upload_to=b'photos'),
        ),
    ]
