# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0006_auto_20180315_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default=b' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='door',
            field=models.CharField(blank=True, default=b' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, default=b' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, default=b' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default=b'00000', max_length=5),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default=b' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='account',
            field=models.CharField(blank=True, default=b' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='month',
            field=models.CharField(blank=True, default=b' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='security_code',
            field=models.CharField(blank=True, default=b' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='year',
            field=models.CharField(blank=True, default=b' ', max_length=4),
        ),
    ]
