# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthylifeapp', '0006_auto_20180311_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='award',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='award_type',
            field=models.IntegerField(choices=[(1, b'Porcentaje'), (2, b'Cantidad')], default=2),
        ),
        migrations.AlterField(
            model_name='award',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthylifeapp.Company'),
        ),
    ]
