# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0006_auto_20180502_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Illnes',
        ),
        migrations.RemoveField(
            model_name='sportsession',
            name='sport_type',
        ),
        migrations.DeleteModel(
            name='SportSession',
        ),
        migrations.DeleteModel(
            name='SportType',
        ),
    ]
