# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 17:09
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0007_auto_20181008_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorprofile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'collaborator_image', '390x450', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='company',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'company_image', '160x160', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
