# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0008_illnes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='web',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
