# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0009_auto_20180312_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='web',
            field=models.CharField(max_length=50, validators=[django.core.validators.URLValidator()]),
        ),
    ]
