# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0009_auto_20180315_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=b'/image.jpg', upload_to=b'photos'),
        ),
    ]
