# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0010_auto_20180312_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default=b'mi empresa', max_length=50),
        ),
    ]
