# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthylifeapp', '0011_auto_20180312_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, default=b' ', max_length=50)),
                ('description', models.TextField()),
                ('privacity', models.IntegerField(choices=[(1, b'P\xc3\xbablico'), (2, b'Privado')], default=1)),
                ('init_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthylifeapp.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ManyToManyField(related_name='event_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
