# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthylifeapp', '0013_auto_20180312_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, b'Publicado'), (2, b'Borrador'), (3, b'Eliminado')], default=2),
        ),
    ]
