# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180724_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Publicado'), (2, 'Pendiente de Revision'), (3, 'Eliminado')], default=2),
        ),
    ]
