# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180725_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='post_tags', to='blog.Tag'),
        ),
    ]
