# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(blank=True, default=' ', max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('privacity', models.IntegerField(blank=True, choices=[(1, 'P\xfablico'), (2, 'Privado')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Deporte'), (2, 'Nutrici\xf3n'), (3, 'Salud')], default=1)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
