# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 13, 47, 12, 953512)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 13, 47, 12, 953481)),
        ),
    ]
