# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180710_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(blank=True, default=2018),
        ),
    ]
