# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180710_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10'), (11, b'11'), (12, b'12'), (13, b'13'), (14, b'14'), (15, b'15'), (16, b'16'), (17, b'17'), (18, b'18'), (19, b'19'), (20, b'20'), (21, b'21'), (22, b'22'), (23, b'23'), (24, b'24'), (25, b'25'), (26, b'26'), (27, b'27'), (28, b'28'), (29, b'29'), (30, b'30')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2018),
        ),
    ]
