# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='type',
            field=models.IntegerField(choices=[(1, 'Definicion'), (2, 'Volumen'), (3, 'Mantenimiento'), (2, 'Adelgazamiento')], default=0),
        ),
    ]
