# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutritionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Definicion'), (2, 'Aumento'), (3, 'Mantenimiento'), (2, 'Adelgazamiento')], default=0)),
                ('calories', models.IntegerField(default=18)),
                ('days', models.IntegerField(default=90)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MacroNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Proteinas'), (2, 'Hidratos'), (3, 'Grasas'), (2, 'Fibra')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MicroNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('size', models.IntegerField(default=175)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sport_frecuency', models.DecimalField(decimal_places=3, max_digits=4)),
                ('sex', models.IntegerField(choices=[(0, ''), (1, 'Hombre'), (2, 'Mujer')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Nutrient',
            new_name='Dish',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='fats',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
