# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_award_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='shop_objects',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
