# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180705_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mark',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='shop.Review'),
        ),
    ]
