# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180725_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=models.IntegerField(choices=[(1, 'Espa\xf1a')], default=1),
        ),
        migrations.AddField(
            model_name='shipping',
            name='province',
            field=models.IntegerField(choices=[(1, 'Espa\xf1a')], default=1),
        ),
        migrations.AddField(
            model_name='shipping',
            name='region',
            field=models.IntegerField(choices=[(1, 'Aragon')], default=1),
        ),
        migrations.AddField(
            model_name='shipping',
            name='time',
            field=models.ImageField(choices=[(1, '24h'), (2, '48h')], default=1, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 0, 35, 3, 163861)),
        ),
    ]
