# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180924_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 18, 37, 21, 428896)),
        ),
    ]
