# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180928_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 11, 31, 36, 364024)),
        ),
    ]
