# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181001_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 12, 24, 5, 127374)),
        ),
    ]
