# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181004_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 18, 29, 45, 615097)),
        ),
    ]
