# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181008_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 18, 47, 3, 443326)),
        ),
    ]
