# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181008_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 19, 9, 28, 497905)),
        ),
    ]
