# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181008_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 21, 31, 45, 962579)),
        ),
    ]
